### ISSUE TITLE
offline quiz still does not work with GDPR plugins

### ISSUE THREAD

**Issue by webers-technikum-wien** [academic-moodle-cooperation/moodle-mod_offlinequiz#105]
making a new issue now, since the old one was not reopened when I reported that it doesnt work (https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/92)

using offline quiz 3.6.2 on moodle 3.6.3, data requests by users are still not processed without error:

Exception occurred while calling mod_offlinequiz\privacy\provider::get_contexts_for_userid.
This means that plugin mod_offlinequiz did not complete the processing of data. The following exception information may be passed on to the plugin developer:

Error reading from database

#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(248): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(764): pgsql_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71): pgsql_native_moodle_database->get_recordset_sql('DECLARE crs79 N...', Array)
#3 /var/www/moodle/mod/offlinequiz/classes/privacy/provider.php(286): core_privacy\local\request\contextlist->add_from_sql('SELECT c.id FRO...', Array)
#4 /var/www/moodle/lib/moodlelib.php(7889): mod_offlinequiz\privacy\provider::get_contexts_for_userid(6869)
#5 /var/www/moodle/privacy/classes/manager.php(578): component_class_callback('mod_offlinequiz...', 'get_contexts_fo...', Array)
#6 /var/www/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /var/www/moodle/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#8 /var/www/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(93): core_privacy\manager->get_contexts_for_userid(6869)
#9 /var/www/moodle/lib/cronlib.php(185): tool_dataprivacy\task\process_data_request_task->execute()
#10 /var/www/moodle/lib/cronlib.php(74): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#11 /var/www/moodle/admin/cli/cron.php(61): cron_run()
#12 {main}

**Comment by goggo24** [comment]
Thanks for reporting. We will fully support GDPR (delete) with v.3.7.0.

**Comment by univietw** [comment]
I tried to find the problem with the query and never ran into it. Do you have any additional information how to reproduce this bug? As I can see you are running moodle on a postgres-database, as I do. Which field do you use as ID-Field? The default (idnumber)? What type of user are you exporting? teacher or student?

Maybe I'm missing something, otherwise I'm out of guesses. It seems like this Issue might only happen occasionaly.

**Comment by webers-technikum-wien** [comment]
in offlinequiz plugin settings we have user identification set to "[5]=id"

the type of user does not really apply - the users who filed an export data request are not even enrolled in any courses that use offlinequiz (we only installed this plugin recently)

since no data actually needs to be deleted, my current workaround was to replace /mod/offlinequiz/classes/privacy/provider.php with one that is default for modules that do not process any data - this eliminates the error messages

here is what cron.php reports when called directly via the web interface:

    mod_journal wird verarbeitet (53/550) (Freitag, 12. Juli 2019, 15:09)
    mod_label wird verarbeitet (54/550) (Freitag, 12. Juli 2019, 15:09)
    mod_lesson wird verarbeitet (55/550) (Freitag, 12. Juli 2019, 15:09)
    mod_lti wird verarbeitet (56/550) (Freitag, 12. Juli 2019, 15:09)
    mod_offlinequiz wird verarbeitet (57/550) (Freitag, 12. Juli 2019, 15:09)
++ Fehler beim Lesen der Datenbank (ERROR:  operator does not exist: bigint = character varying
LINE 24:                 JOIN mdl_user u ON u.id = sp.userkey
                                                 ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

                  SELECT ctx.id AS ctxid, ctx.path AS ctxpath, ctx.depth AS ctxdepth, ctx.contextlevel AS ctxlevel, ctx.instanceid AS ctxinstance, ctx.locked AS ctxlocked
                    FROM mdl_context ctx
                    JOIN (SELECT c.id FROM mdl_context c
        JOIN mdl_course_modules cm ON cm.id = c.instanceid
        JOIN mdl_modules m ON m.id = cm.module AND m.name = 'offlinequiz'
        AND cm.instance IN (
            SELECT l.offlinequizid id
                FROM mdl_offlinequiz_p_lists l
                JOIN mdl_offlinequiz_participants p on l.id = p.listid
                WHERE userid = $1
            UNION ALL
                SELECT p.offlinequizid id
                FROM mdl_offlinequiz_scanned_p_pages p
                JOIN mdl_offlinequiz_p_choices c ON p.id = c.scannedppageid
                WHERE c.userid = $2
            UNION ALL
                SELECT q.offlinequizid id
                FROM mdl_offlinequiz_queue q
                WHERE importuserid = $3
            UNION ALL
                SELECT sp.offlinequizid id
                FROM mdl_offlinequiz_scanned_pages sp
                JOIN mdl_user u ON u.id = sp.userkey
                WHERE u.id = $4)) target ON ctx.id = target.id
[array (
  0 => 5725,
  1 => 5725,
  2 => 5725,
  3 => 5725,
)]) ++
* line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()

**Comment by univietw** [comment]
OK, now I understand. But this is a problem for itself, because the plugin expects the ID-Field to be a character Type and not an Integer Type. The thing is, that users with an ID with leading 0 would not work at the moment, because it tries to compare it with the content of the column "userkey" which is, in fact, a string.

So for a quickfix for you, you can change the identification to "[5]=idnumber", that will probably fix your issue. I will discuss how to deal with that problem internally, because supporting number columns will be a little bit more complicated than fixing a small issue :)

**Comment by webers-technikum-wien** [comment]
That is not a quickfix for me, since i already specifically adapted the plugin to use [id] instead of [idnumber] (reason: our idnumbers are alphanumeric, not numeric).

There were other issues with not using [id] as well, so while the plugin seemed to support other id fields, it did not actually do so (see fixed issues). We are now successfully using it with [id], so this seems to be the last problem that remains :)

I doubt it has to do with leading 0s - i just tried deleting a user with a 5 digit id and had the same problem...

**Comment by univietw** [comment]
good to know. I always had in mind that it only works with character fields. I will find a solution. Thanks

**Comment by univietw** [comment]
i fixed this in the master branch as wished. Can you test if it would work like that in your instance?

**Comment by webers-technikum-wien** [comment]
cron.php now runs without any errors, but after running i still get a modmail from moodle with this:

Beim Aufruf von MOD_OFFLINEQUIZ\PRIVACY\PROVIDER::GET_CONTEXTS_FOR_USERID
ist ein Fehler aufgetreten.
Das Plugin MOD_OFFLINEQUIZ hat die Verarbeitung der Daten nicht beendet.
Unten finden Sie Informationen für den Pluginentwickler.
Fehler beim Lesen der Datenbank
#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(248):
moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(764):
pgsql_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71):
pgsql_native_moodle_database->get_recordset_sql('DECLARE crs79 N...', Array)
#3 /var/www/moodle/mod/offlinequiz/classes/privacy/provider.php(286):
core_privacy\local\request\contextlist->add_from_sql('SELECT c.id FRO...', Array)
#4 /var/www/moodle/lib/moodlelib.php(7889):
mod_offlinequiz\privacy\provider::get_contexts_for_userid(6024)
#5 /var/www/moodle/privacy/classes/manager.php(578):

**Comment by univietw** [comment]
Ive forgotten one of the declations. Now it shout work :)

**Comment by webers-technikum-wien** [comment]
no, unfortunately still the same thing:
Beim Aufruf von MOD_OFFLINEQUIZ\PRIVACY\PROVIDER::GET_CONTEXTS_FOR_USERID
ist ein Fehler aufgetreten.
Das Plugin MOD_OFFLINEQUIZ hat die Verarbeitung der Daten nicht beendet.
Unten finden Sie Informationen für den Pluginentwickler.
Fehler beim Lesen der Datenbank
#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(248):
moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(764):
pgsql_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71):
pgsql_native_moodle_database->get_recordset_sql('DECLARE crs78 N...', Array)
#3 /var/www/moodle/mod/offlinequiz/classes/privacy/provider.php(290):
core_privacy\local\request\contextlist->add_from_sql('SELECT c.id FRO...', Array)
#4 /var/www/moodle/lib/moodlelib.php(7945):
mod_offlinequiz\privacy\provider::get_contexts_for_userid(4367)
#5 /var/www/moodle/privacy/classes/manager.php(578):

**Comment by goggo24** [comment]
Privacy Api is now fully supported (delete) with v.3.8.0. 
@webers-technikum-wien: does it work for you too (with postgress)?

**Comment by webers-technikum-wien** [comment]
unfortunately not, but i think it might not be a postgres issue, but rather because we are using the moodle id as an identifier - we still get an error from cron upon accepting the deletion request:

```
Fehler beim Lesen der Datenbank (ERROR:  column "spuserkey" does not exist
LINE 23: ..._scanned_pages sp JOIN mdl_user u ON u.id =  CAST(spuserkey ...
                                                              ^
HINT:  Perhaps you meant to reference the column "sp.userkey".

                  SELECT ctx.id AS ctxid, ctx.path AS ctxpath, ctx.depth AS ctxdepth, ctx.contextlevel AS ctxlevel, ctx.instanceid AS ctxinstance, ctx.locked AS ctxlocked
                    FROM mdl_context ctx
                    JOIN (SELECT c.id FROM mdl_context c
        JOIN mdl_course_modules cm ON cm.id = c.instanceid
        JOIN mdl_modules m ON m.id = cm.module AND m.name = 'offlinequiz'
        AND cm.instance IN (
            SELECT l.offlinequizid id
                FROM mdl_offlinequiz_p_lists l
                JOIN mdl_offlinequiz_participants p on l.id = p.listid
                WHERE userid = $1
            UNION ALL
                SELECT p.offlinequizid id
                FROM mdl_offlinequiz_scanned_p_pages p
                JOIN mdl_offlinequiz_p_choices c ON p.id = c.scannedppageid
                WHERE c.userid = $2
            UNION ALL
                SELECT q.offlinequizid id
                FROM mdl_offlinequiz_queue q
                WHERE importuserid = $3
            UNION ALL
                SELECT sp.offlinequizid id
                FROM mdl_offlinequiz_scanned_pages sp JOIN mdl_user u ON u.id =  CAST(spuserkey AS INT)  WHERE u.id = $4)) target ON ctx.id = target.id
[array (
  0 => 5974,
  1 => 5974,
  2 => 5974,
  3 => 5974,
)])


#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(259): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(776): pgsql_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71): pgsql_native_moodle_database->get_recordset_sql('DECLARE crs65 N...', Array)
#3 /var/www/moodle/mod/offlinequiz/classes/privacy/provider.php(292): core_privacy\local\request\contextlist->add_from_sql('SELECT c.id FRO...', Array)
#4 /var/www/moodle/lib/moodlelib.php(7980): mod_offlinequiz\privacy\provider::get_contexts_for_userid(5974)
#5 /var/www/moodle/privacy/classes/manager.php(578): component_class_callback('mod_offlinequiz...', 'get_contexts_fo...', Array)
#6 /var/www/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /var/www/moodle/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#8 /var/www/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(94): core_privacy\manager->get_contexts_for_userid(5974)
#9 /var/www/moodle/lib/cronlib.php(284): tool_dataprivacy\task\process_data_request_task->execute()
#10 /var/www/moodle/lib/cronlib.php(166): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#11 /var/www/moodle/lib/cronlib.php(76): cron_run_adhoc_tasks(1583746178)
#12 /var/www/moodle/admin/cron.php(81): cron_run()
#13 {main}
```
