### ISSUE TITLE
error creating forms after upgrading to v3.3.0

### ISSUE THREAD

**Issue by nibar** [academic-moodle-cooperation/moodle-mod_offlinequiz#42]
Just after upgrading to offline quiz v3.3.0 I get a database writing error. It seems that possible causes are either limited max exec packet size or db table format. I run moodle 3.3+ and I still have db tables in Antelope but till the plug in upgrade I did not experience any problem with offline quiz (v3.2.2
2017020202).

In Debug I get: Notice: Undefined index: id_digits in /var/www/vhosts/mysite/httpdocs/lib/dml/mysqli_native_moodle_database.php on line 1544

**Comment by univietw** [comment]
I had the same issues. The only thing that worked for me on my local installation was converting the tables described here https://docs.moodle.org/33/en/Administration_via_command_line#Converting_InnoDB_tables_to_Barracuda
I don't know if anyone tried this solution for the problem on a productive instance though, so please make an update before doing that.

**Comment by nibar** [comment]
Thank you very much for yor reply, I tried the same solution and the problem was resolved.

I also changed the version of the database server to the last available.

Best regards,

Nikos Barotsis

**Comment by univietw** [comment]
I'll close this issue then :)

**Comment by dashohoxha** [comment]
I still have this issue. At **Create forms / PDF forms** I get this error message: "_Error writing to database_".

This is a new moodle installation (Moodle 3.3.1+ (Build: **20170810**)) and the latest version of mod_offlinequiz (v3.3.0, **2017081100**).

I have tried with previous versions of mod_offlinequiz, and PDF form generation works only with version **2016072301** (I have forced the installation of the old version with: `moosh plugin-install -f mod_offlinequiz 2016072301`)

I have tried the command `php admin/cli/mysql_compressed_rows.php`, that is suggested above, but it  does not fix it.

So, I think that this issue should be re-opened, or I should create a new one.

**Comment by juzi** [comment]
Could you switch  debugging to developer level and post the complete error message?

**Comment by dashohoxha** [comment]
```
Notice: Undefined index: id_digits in /var/www/moodle/lib/dml/mysqli_native_moodle_database.php on line 1559
```

```
Debug info: Unknown column 'id_digits' in 'field list'
UPDATE mdl_offlinequiz SET id_digits = ? WHERE id = ?
[array (
0 => '7',
1 => '9',
)]
Error code: dmlwriteexception
```

```
Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1574 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1780 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->set_field_select()
line 416 of /mod/offlinequiz/createquiz.php: call to moodle_database->set_field()
```

**Comment by dashohoxha** [comment]
I upgrade Moodle by first making a dump of the database, then installing the new version, then a restore of the database:
 - https://github.com/docker-scripts/moodle/blob/master/cmd/backup.sh#L35
 - https://github.com/docker-scripts/moodle/blob/master/cmd/restore.sh#L34

Then I run `php admin/cli/upgrade.php --non-interactive`:
 - https://github.com/docker-scripts/moodle/blob/master/cmd/upgrade.sh#L27

Maybe this process fails to upgrade the DB structure correctly (hence the missing column)?

**Comment by univietw** [comment]
It seems that the sql creating the column is not executed. I tested the creation of this feature only on the website, without calling upgrade.php directly. The error here is defenitely another one. Would you mind creating a new Error? You can solve this error by just executing the php for version 2017020202 in the upgrade.php again.

**Comment by dashohoxha** [comment]
I created a new issues: #45
