### ISSUE TITLE
offline quiz does not seem to support moodle GDPR plugins

### ISSUE THREAD

**Issue by webers-technikum-wien** [academic-moodle-cooperation/moodle-mod_offlinequiz#92]
I just deleted users using the Moodle GDPR plugins, where deleting users creates a data request for deletion, and upon approving that it is supposed to delete all personal data from all plugins.

The only installed plugin (out of 40+) on our site that threw an error was offline quiz, so I guess its GDPR implementation is broken:

Beim Aufruf von mod_offlinequiz\privacy\provider::get_contexts_for_userid ist ein Fehler aufgetreten.
Das Plugin mod_offlinequiz hat die Verarbeitung der Daten nicht beendet. Unten finden Sie Informationen für den Pluginentwickler.

Fehler beim Lesen der Datenbank

#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(248): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(764): pgsql_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71): pgsql_native_moodle_database->get_recordset_sql('DECLARE crs554 ...', Array)
#3 /var/www/moodle/mod/offlinequiz/classes/privacy/provider.php(282): core_privacy\local\request\contextlist->add_from_sql('SELECT c.id FRO...', Array)
#4 /var/www/moodle/lib/moodlelib.php(7858): mod_offlinequiz\privacy\provider::get_contexts_for_userid(14557)
#5 /var/www/moodle/privacy/classes/manager.php(578): component_class_callback('mod_offlinequiz...', 'get_contexts_fo...', Array)
#6 /var/www/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /var/www/moodle/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#8 /var/www/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(93): core_privacy\manager->get_contexts_for_userid(14557)
#9 /var/www/moodle/lib/cronlib.php(185): tool_dataprivacy\task\process_data_request_task->execute()
#10 /var/www/moodle/lib/cronlib.php(74): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#11 /var/www/moodle/admin/cron.php(81): cron_run()
#12 {main}

**Comment by univietw** [comment]
Did you use the newest offlinequiz version? There was a bug that was fixed in the newest 3.6.2

**Comment by univietw** [comment]
OK, I just realized, 3.6.2 is not yet released, it will be released very soon.

**Comment by webers-technikum-wien** [comment]
OK awesome, did you see my other issue about oumultiresponse not being supported? should I just send you the code so you can maybe incorporate that into 3.6.2 as well? As i mentioned in the other ticket, its basically just including that additional question type in all the if-statements that sort for question type.

**Comment by univietw** [comment]
OK, my fault. It should be fixed in 3.6.1

**Comment by goggo24** [comment]
v3.6.1 already published - v.3.6.2 will come soon.

**Comment by webers-technikum-wien** [comment]
@univietw FYI:

i just ran into the same bug with v3.6.1 2019012901 again - so it's not fixed in v3.6.1

it worked with v3.6.2 2019012902, so it seems to be fixed there

**Comment by webers-technikum-wien** [comment]
actually, it does not work in v.3.6.2 either. at least it does not completely stop cron from running, but cron still reports an error:

Beim Aufruf von mod_offlinequiz\privacy\provider::get_contexts_for_userid ist ein Fehler aufgetreten.
Das Plugin mod_offlinequiz hat die Verarbeitung der Daten nicht beendet. Unten finden Sie Informationen für den Pluginentwickler.

Fehler beim Lesen der Datenbank


#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(248): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(764): pgsql_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71): pgsql_native_moodle_database->get_recordset_sql('DECLARE crs61 N...', Array)
#3 /var/www/moodle/mod/offlinequiz/classes/privacy/provider.php(286): core_privacy\local\request\contextlist->add_from_sql('SELECT c.id FRO...', Array)
#4 /var/www/moodle/lib/moodlelib.php(7858): mod_offlinequiz\privacy\provider::get_contexts_for_userid(16858)
#5 /var/www/moodle/privacy/classes/manager.php(578): component_class_callback('mod_offlinequiz...', 'get_contexts_fo...', Array)
#6 /var/www/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /var/www/moodle/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('mod_offlinequiz', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#8 /var/www/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(93): core_privacy\manager->get_contexts_for_userid(16858)
#9 /var/www/moodle/lib/cronlib.php(185): tool_dataprivacy\task\process_data_request_task->execute()
#10 /var/www/moodle/lib/cronlib.php(74): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#11 /var/www/moodle/admin/cli/cron.php(61): cron_run()
#12 {main}
